CREATE DATABASE gotogrodatabase
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE gotogrodatabase;

CREATE TABLE staff (
	staff_id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(30) NOT NULL,
	middle_name VARCHAR(30),
	last_name VARCHAR(30) NOT NULL,
	date_of_birth DATE NOT NULL,
	street VARCHAR(50),
	city VARCHAR(30),
	state VARCHAR(30),
	zip CHAR(9),
	password VARBINARY(255) NOT NULL,
	email VARCHAR(100) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE member (
	member_id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(30) NOT NULL,
	middle_name VARCHAR(30),
	last_name VARCHAR(30) NOT NULL,
	date_of_birth DATE NOT NULL,
	street VARCHAR(50),
	city VARCHAR(30),
	state VARCHAR(30),
	zip CHAR(9),
	email VARCHAR(100) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE product (
	product_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	supplier VARCHAR(30) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB; 

CREATE TABLE sale (
	sale_id INT AUTO_INCREMENT PRIMARY KEY,
	member_id INT NOT NULL,
	staff_id INT NOT NULL,
	sale_date DATE NOT NULL,
	FOREIGN KEY (member_id) REFERENCES member(member_id),
    FOREIGN KEY (staff_id) REFERENCES staff(staff_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sale_line (
	sale_id INT NOT NULL,
	line_number INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY (sale_id, line_number),
	FOREIGN KEY (sale_id) REFERENCES sale(sale_id),
	FOREIGN KEY (product_id) REFERENCES product(product_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE role (
	role_id INT AUTO_INCREMENT PRIMARY KEY,
	role_name VARCHAR(50) NOT NULL UNIQUE,
	description VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE staff_role (
	staff_id INT NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (staff_id, role_id),
	FOREIGN KEY (staff_id) REFERENCES staff(staff_id),
	FOREIGN KEY (role_id) REFERENCES role(role_id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
