CREATE DATABASE gotogrodatabase
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE gotogrodatabase;

CREATE TABLE staff (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	middle_name VARCHAR(50),
	last_name VARCHAR(50) NOT NULL,
	date_of_birth DATE NOT NULL,
	street VARCHAR(255),
	city VARCHAR(100),
	state CHAR(10),
	zip CHAR(10),
	password VARBINARY(255) NOT NULL,
	email VARCHAR(100) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL UNIQUE,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE members (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	middle_name VARCHAR(50),
	last_name VARCHAR(50) NOT NULL,
	date_of_birth DATE NOT NULL,
	street VARCHAR(255),
	city VARCHAR(100),
	state CHAR(2),
	zip CHAR(10),
	email VARCHAR(100) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL UNIQUE,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	supplier VARCHAR(255) NOT NULL,
	price DECIMAL(8,2) NOT NULL,
	description TEXT,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sales (
	id INT AUTO_INCREMENT PRIMARY KEY,
	member_id INT NOT NULL,
	staff_id INT NOT NULL,
	sale_date DATE NOT NULL,
	FOREIGN KEY (member_id) REFERENCES members(id),
    FOREIGN KEY (staff_id) REFERENCES staff(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE sale_lines (
	sale_id INT NOT NULL,
	line_number INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY (sale_id, line_number),
	FOREIGN KEY (sale_id) REFERENCES sales(id),
	FOREIGN KEY (product_id) REFERENCES products(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE roles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	description VARCHAR(255),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE staff_roles (
	staff_id INT NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (staff_id, role_id),
	FOREIGN KEY (staff_id) REFERENCES staff(id),
	FOREIGN KEY (role_id) REFERENCES roles(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
