import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8765/staff/login?redirect=%2F');
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('ennisthomashenry');
  await page.getByLabel('Email').press('Tab');
  await page.getByLabel('Password').fill('passowrd');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('ennisthomashenry@gmail.com');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('http://localhost:8765/members/add');
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('Test');
  await page.getByLabel('First Name').press('Tab');
  await page.getByLabel('Middle Name').fill('Yser');
  await page.getByLabel('Last Name').click();
  await page.getByLabel('Last Name').fill('Ennis');
  await page.getByLabel('Date Of Birth').fill('2000-01-22');
  await page.getByLabel('Street').click();
  await page.getByLabel('Street').fill('South');
  await page.getByLabel('Street').press('ArrowLeft');
  await page.getByLabel('Street').press('ArrowLeft');
  await page.getByLabel('Street').press('ArrowLeft');
  await page.getByLabel('Street').press('ArrowLeft');
  await page.getByLabel('Street').press('ArrowLeft');
  await page.getByLabel('Street').fill('12 South');
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('Melbourne');
  await page.locator('div').filter({ hasText: /^Zip$/ }).first().click();
  await page.getByLabel('Zip').fill('1231');
  await page.getByRole('combobox').selectOption('VIC');
  await page.getByRole('combobox').click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('Ennisthomashenry@');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').fill('Ennisthomashenry22@');
  await page.getByLabel('Email').press('ArrowRight');
  await page.getByLabel('Email').press('ArrowRight');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').press('ArrowRight');
  await page.getByLabel('Email').fill('Ennisthomashenry22@gmail.com');
  await page.getByRole('button', { name: 'Submit' }).click();
});